# Generated by Django 4.0.1 on 2022-01-14 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('dealer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dealer_img', models.ImageField(upload_to='')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('contact', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('dealer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_name', to=settings.AUTH_USER_MODEL)),
                ('dealer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
