# Generated by Django 4.0.1 on 2022-01-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_name',
            field=models.CharField(max_length=100),
        ),
    ]
